# .goreleaser.yml
builds:
  - binary: dnaquery
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    darwin: macOS
