[storage]
LogDirectory = 'logs'

[[containers]]
    Name = "production-app"
    Regex = '^([\d.]+) - \[([^\]]*)\] - - \[([^\]]*)\] "([^"]*)" (\d+) (\d+) "([^"]*)" "([^"]*)" (\d+) ([\d.]+) ([\d.:]+) (\d+) ([\d.]+) (\d+)$'
    TimeGroup = 3
    TimeFormat = "2/Jan/2006:15:04:05 -0700"
    [[containers.excludes]]
        Group = 4
        Contains = "ping"

[gcp]
ProjectID = "gcpproj"
CredentialsFile = "gcp_credentials.json"
UploadBucket = "logdna_to_bq"
Dataset = "logdna"
TemplateTable = "logdna"
LogPrefix = "a7112abc9d"
LogBucket = "logs"
